[theme]
base = "light"
primaryColor = "#D45D45"
backgroundColor = "#F3EFE7"
secondaryBackgroundColor = "#E8E1D5"
textColor = "#20211D"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
