[theme]
base = "light"
primaryColor = "#B85C43"
backgroundColor = "#F7F3EC"
secondaryBackgroundColor = "#EEE8DE"
textColor = "#25211D"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
